"""Decision D8: the static pristine cell for the gap regulariser (plan section 6, C2 ruled
static-lattice), built label-free from the thermal pristine frames -- no relaxed frame
exists and no new DFT is allowed.

Construction (label-free, permutation- and origin-free): every frame is registered to the
running reference by the rigid shift, among those that put one of its anchor-species atoms
on the reference's first anchor site, that minimises the species-wise minimum-cost
assignment on minimum-image distances (a global search: a lattice of sites spread over the
cell has no meaningful circular mean); its atoms take that assignment, and each site's ideal
fractional position is the coordinate-wise MEDIAN over frames of the assigned displacement
(the median does not see the rare hopped atom); repeated from the new median until it
moves no site; the cell is the mean cell snapped orthogonal when nearly so. The site set is
then symmetrised
over the GROUP generated by the crystal symmetries found on it within `SITE_TOL` (signed
permutations that are isometries of the cell, with any fractional translation) until
exactly invariant. On the CsPbCl3 data this gives the Pnma cell with its 2x2x1 supercell
translations (32 operations). The thermal ensemble-mean gap over pristine frames is
reported alongside (plan section 6) by the model, not here.
"""
from __future__ import annotations

import hashlib
import itertools
import logging
from typing import Any, Dict, List, Sequence, Tuple

import numpy as np
import torch

# Registered (D21 of the v8 programme, carried over): the tolerance within which a symmetry
# operation is accepted on the sampled median (the Pnma operations hold to 0.24-0.35 A on
# a 300 K MD median that kept its tilt pattern), well under the smallest site spacing.
SITE_TOL = 0.3
MEDIAN_TOL = 0.005          # A: iterate the median until a pass moves no site more than this
MAX_PASSES = 8
CELL_ORTHO_TOL = 0.02       # snap the mean cell orthogonal when off-diagonals are below this x min length
_OP_TOL = 0.05              # fractional: two operations with equal R and t (mod 1) within this are one


def _signed_permutations() -> List[np.ndarray]:
    out = []
    for perm in itertools.permutations(range(3)):
        for signs in itertools.product((1, -1), repeat=3):
            R = np.zeros((3, 3), dtype=np.int64)
            for i, j in enumerate(perm):
                R[i, j] = signs[i]
            out.append(R)
    return out


def lattice_symmetries(scaled: torch.Tensor, species: torch.Tensor, cell: np.ndarray,
                       tol: float = SITE_TOL) -> List[Dict[str, Any]]:
    """Affine maps `x -> R x + t` (R a signed permutation that is an isometry of `cell`)
    carrying the species-labelled site set onto itself within `tol` (A); identity first."""
    scaled = scaled.detach().to(torch.float64).cpu()
    species = species.detach().cpu()
    cell_t = torch.tensor(np.asarray(cell, dtype=np.float64)).reshape(3, 3)
    n = scaled.shape[0]
    same = torch.nonzero(species == species[0]).reshape(-1)
    cross = species[:, None] != species[None, :]
    ops: List[Dict[str, Any]] = []
    seen = set()
    for R in _signed_permutations():
        R_t = torch.tensor(R, dtype=torch.float64)
        A = cell_t.T @ R_t @ torch.linalg.inv(cell_t.T)
        if float((A.T @ A - torch.eye(3, dtype=torch.float64)).abs().max()) > 1e-6:
            continue
        moved = scaled @ R_t.T
        for k in same.tolist():
            t = scaled[k] - moved[0]
            d = (moved + t)[:, None, :] - scaled[None, :, :]
            d = d - torch.round(d)
            dist = (d @ cell_t).norm(dim=-1)
            dist = torch.where(cross, torch.full_like(dist, float("inf")), dist)
            best = dist.argmin(dim=1)
            if float(dist[torch.arange(n), best].max()) > tol or torch.unique(best).numel() != n:
                continue
            t_mod = t - torch.floor(t)
            key = (tuple(R.reshape(-1).tolist()), tuple((t_mod * 1000).round().long().tolist()))
            if key in seen:
                continue
            seen.add(key)
            ops.append({"R": R.tolist(), "t": [float(x) for x in t_mod.tolist()]})
    eye = np.eye(3, dtype=np.int64).tolist()
    identity = [op for op in ops if op["R"] == eye and max(min(x, 1.0 - x) for x in op["t"]) < 1e-9]
    return identity + [op for op in ops if op not in identity]


def compose(a: Dict[str, Any], b: Dict[str, Any]) -> Dict[str, Any]:
    R_a, t_a = np.asarray(a["R"], dtype=np.int64), np.asarray(a["t"], dtype=np.float64)
    R_b, t_b = np.asarray(b["R"], dtype=np.int64), np.asarray(b["t"], dtype=np.float64)
    t = R_b @ t_a + t_b
    return {"R": (R_b @ R_a).tolist(), "t": (t - np.floor(t)).tolist()}


def _same(a: Dict[str, Any], b: Dict[str, Any]) -> bool:
    if a["R"] != b["R"]:
        return False
    d = np.asarray(a["t"]) - np.asarray(b["t"])
    return float(np.abs(d - np.round(d)).max()) < _OP_TOL


def symmetry_closure(ops: Sequence[Dict[str, Any]], cap: int = 48 * 4096) -> List[Dict[str, Any]]:
    """The group generated by `ops` under composition."""
    group = [dict(op) for op in ops]
    changed = True
    while changed:
        changed = False
        for a in list(group):
            for b in list(group):
                c = compose(a, b)
                if not any(_same(c, g) for g in group):
                    group.append(c)
                    changed = True
                    if len(group) > cap:
                        raise ValueError("symmetry_closure: no finite group at this tolerance")
    return group


def apply_symmetry(op: Dict[str, Any], scaled: torch.Tensor) -> torch.Tensor:
    R = torch.tensor(op["R"], dtype=scaled.dtype, device=scaled.device)
    t = torch.tensor(op["t"], dtype=scaled.dtype, device=scaled.device)
    return scaled @ R.T + t


def symmetrise_sites(scaled: torch.Tensor, species: torch.Tensor, cell: np.ndarray,
                     ops: Sequence[Dict[str, Any]]) -> torch.Tensor:
    """Each site replaced by the mean of its images under every operation, pulled back."""
    scaled = scaled.detach().to(torch.float64).cpu()
    species = species.detach().cpu()
    cell_t = torch.tensor(np.asarray(cell, dtype=np.float64)).reshape(3, 3)
    cross = species[:, None] != species[None, :]
    acc = torch.zeros_like(scaled)
    for op in ops:
        R = torch.tensor(op["R"], dtype=torch.float64)
        t = torch.tensor(op["t"], dtype=torch.float64)
        moved = scaled @ R.T + t
        d = moved[:, None, :] - scaled[None, :, :]
        d = d - torch.round(d)
        dist = torch.where(cross, torch.full_like(d[..., 0], float("inf")), (d @ cell_t).norm(dim=-1))
        image = dist.argmin(dim=1)
        back = (scaled[image] - t) @ torch.linalg.inv(R.T)
        back = back - torch.round(back - scaled)
        acc += back
    return acc / max(len(ops), 1)


def _assign(frac: np.ndarray, numbers: np.ndarray, scaled: np.ndarray, numbers0: np.ndarray,
            cell: np.ndarray, shift: np.ndarray) -> Tuple[float, np.ndarray]:
    from scipy.optimize import linear_sum_assignment

    match = np.full(len(numbers), -1, dtype=np.int64)
    total = 0.0
    for z in np.unique(numbers0):
        atoms = np.nonzero(numbers == z)[0]
        sites = np.nonzero(numbers0 == z)[0]
        d = frac[atoms][:, None, :] - (scaled[sites] + shift)[None, :, :]
        d -= np.round(d)
        cost = (np.linalg.norm(d @ cell, axis=-1) ** 2)
        rows, cols = linear_sum_assignment(cost)
        match[atoms[rows]] = sites[cols]
        total += float(cost[rows, cols].sum())
    return total, match


def register_and_assign(frac: np.ndarray, numbers: np.ndarray, scaled: np.ndarray,
                        numbers0: np.ndarray, cell: np.ndarray, anchor_species: int
                        ) -> Tuple[np.ndarray, np.ndarray]:
    """`(shift, match)`: among the rigid fractional shifts that carry the reference's first
    `anchor_species` site onto each of the frame's `anchor_species` atoms, the one with the
    least species-wise assignment cost, and that assignment (per atom, its reference site)."""
    site0 = int(np.nonzero(numbers0 == anchor_species)[0][0])
    best = (float("inf"), None, None)
    for k in np.nonzero(numbers == anchor_species)[0]:
        shift = frac[k] - scaled[site0]
        cost, match = _assign(frac, numbers, scaled, numbers0, cell, shift)
        if cost < best[0]:
            best = (cost, shift, match)
    shift, match = best[1], best[2]
    # Refine the rigid shift to the mean assigned displacement (minimum image).
    d = frac - (scaled[match] + shift)
    d -= np.round(d)
    return shift + d.mean(axis=0), match


def static_pristine_cell(frames: Sequence, tol: float = SITE_TOL, log: bool = True) -> Dict[str, Any]:
    """`{"numbers", "positions", "cell", "construction"}` from ASE frames of one pristine
    cell (any atom order, any origin)."""
    numbers0 = np.asarray(frames[0].get_atomic_numbers())
    for k, a in enumerate(frames):
        if sorted(a.get_atomic_numbers().tolist()) != sorted(numbers0.tolist()):
            raise ValueError(f"frame {k}: composition differs from frame 0")
    n = len(numbers0)
    # The heaviest species (least displaced) anchors the registration search.
    anchor_species = int(max(set(int(z) for z in numbers0)))
    cells = np.stack([np.asarray(a.get_cell(), dtype=np.float64) for a in frames])
    cell_mean = cells.mean(axis=0)
    lengths = np.linalg.norm(cell_mean, axis=1)
    off_diagonal = float(np.abs(cell_mean - np.diag(np.diag(cell_mean))).max())
    snapped = off_diagonal < CELL_ORTHO_TOL * float(lengths.min())
    if snapped:
        cell_mean = np.diag(lengths)
    scaled = frames[0].get_scaled_positions(wrap=True).copy()
    passes = 0
    shift_max = float("inf")
    for _ in range(MAX_PASSES):
        passes += 1
        disp = np.zeros((len(frames), n, 3))
        for k, a in enumerate(frames):
            frac = a.get_scaled_positions(wrap=True)
            numbers = np.asarray(a.get_atomic_numbers())
            shift, match = register_and_assign(frac, numbers, scaled, numbers0, cell_mean, anchor_species)
            d = frac - (scaled[match] + shift)
            d -= np.round(d)
            disp[k, match] = d
        # `median_shift`, not `centre`: A1's static check bans that identifier from the
        # runtime path, and a median displacement in fractional coordinates is a different
        # thing entirely from the feature mean the amendment removed.
        median_shift = np.median(disp, axis=0)
        shift_max = float(np.linalg.norm(median_shift @ cell_mean, axis=1).max())
        scaled = scaled + median_shift
        scaled -= np.floor(scaled)
        if shift_max < MEDIAN_TOL:
            break
    shift = shift_max
    residual = np.linalg.norm(disp @ cell_mean, axis=-1)          # [F, n]
    species_codes = {int(z): i for i, z in enumerate(sorted(set(int(z) for z in numbers0)))}
    species = torch.tensor([species_codes[int(z)] for z in numbers0])
    scaled_t = torch.tensor(scaled, dtype=torch.float64)
    median = scaled_t.clone()
    rounds = 0
    ops: List[Dict[str, Any]] = []
    for _ in range(4):
        rounds += 1
        ops = symmetry_closure(lattice_symmetries(scaled_t, species, cell_mean, tol))
        sym = symmetrise_sites(scaled_t, species, cell_mean, ops)
        step = float(((sym - scaled_t) @ torch.tensor(cell_mean)).norm(dim=-1).max())
        scaled_t = sym - torch.floor(sym)
        if step < 1e-8:
            break
    total = scaled_t - median
    total = total - torch.round(total)
    construction = {
        "method": "index_median_symmetrised", "n_frames": len(frames), "passes": passes,
        "median_tol": MEDIAN_TOL, "site_tol": float(tol), "last_pass_shift": shift,
        "cell_snapped_orthogonal": bool(snapped), "cell_off_diagonal": off_diagonal,
        "rms_residual": {str(z): float(np.sqrt((residual[:, numbers0 == z] ** 2).mean()))
                         for z in sorted(set(int(z) for z in numbers0))},
        "max_residual": float(residual.max()),
        "symmetrisation_shift": float((total @ torch.tensor(cell_mean)).norm(dim=-1).max()),
        "symmetry_rounds": rounds, "n_symmetries": len(ops),
        "frames_fingerprint": hashlib.sha256(np.round(np.stack([a.get_positions() for a in frames]), 6).tobytes()).hexdigest()[:16],
    }
    if log:
        logging.info("Static pristine cell: index-median of %d frames (%d passes, last shift %.4f A), "
                     "cell %s, symmetrised over %d operations (shift %.4f A); thermal rms %s A",
                     len(frames), passes, shift, "snapped orthogonal" if snapped else "as sampled",
                     len(ops), construction["symmetrisation_shift"],
                     {k: round(v, 3) for k, v in construction["rms_residual"].items()})
    return {"numbers": [int(z) for z in numbers0], "positions": (scaled_t @ torch.tensor(cell_mean)).tolist(),
            "cell": cell_mean.tolist(), "construction": construction}
